name: Build and Push fotoshow Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/fotoshow

jobs:
  build:
    name: Build Quarkus app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Checkout fotoshow source
        uses: actions/checkout@v4
        with:
          repository: markdooremaal/fotoshow
          path: fotoshow
          fetch-depth: 1

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x fotoshow/gradlew

      - name: Build Quarkus app using Gradle
        run: |
          cd fotoshow
          ./gradlew quarkusBuild --no-daemon

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-build
          path: fotoshow/build/quarkus-app

  docker:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Quarkus build
        uses: actions/download-artifact@v4
        with:
          name: quarkus-build
          path: build/quarkus-app

      - name: Checkout fotoshow source
        uses: actions/checkout@v4
        with:
          repository: markdooremaal/fotoshow
          path: fotoshow
          fetch-depth: 1

      - name: Move build output into source
        run: |
          mkdir -p fotoshow/build
          mv build/quarkus-app fotoshow/build/quarkus-app

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd fotoshow
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest
